# Generated by Django 4.2.2 on 2023-07-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_slug_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='bagher', max_length=80),
        ),
    ]
